package Vocabulary;


import java.io.Serializable;

public enum PartOfSpeech implements Serializable {
	PERIOD, COMMA, QUESTION_MARK, EXCLAMATION_MARK, ARTICLE, ADJECTIVE, ADVERB, 
	CONJUNCTION, INTERJECTION, NOUN, 
	SUBJECT_PRONOUN, OBJECT_PRONOUN, POSSESSIVE_PRONOUN,
	INDEFINITE_PRONOUN, RELATIVE_PRONOUN, 
	INTENSIVE_PRONOUN, DEMONSTRATIVE_PRONOUN, INTERROGATIVE_PRONOUN,
	PREPOSITION, ACTION_VERB, LINKING_VERB, HELPING_VERB, UNKNOWN;
}
